remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: PAGE TITLE
description: page description

navigation:
  - name: ABOUT
    url: about.md
  - name: SECTION 2
    url: sec.md

github:
  is_project_page: false
