remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: TELMO PÉREZ IZQUIERDO
logo: files/pics/Photo.png

navigation:
  - name: RESEARCH
    url: research
  - name: TEACHING
    url: teaching
  - name: CV
    url: cv


github:
  is_project_page: false
